stages: 
  - build
  - archive

image: python:3.7-alpine

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE

build:
  stage: build
  script:
    - apk add --no-cache make rsync
    - pip install pipenv
    - make build
  artifacts:
    paths:
      - dist/


.unit_test:
  stage: test
  script:
    - make test


.doc_tests:
  stage: test
  script:
    - make doc_tests


.archive: &archive
  stage: archive
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$BUILD_VER
    - docker push $IMAGE_NAME:$BUILD_VER


archive_master_build:
  variables:
    BUILD_VER: $CI_COMMIT_REF_NAME
  only:
    - master
  <<: *archive
  

archive_tag:
  variables:
    BUILD_VER: $CI_COMMIT_TAG
  only:
    - tags
  <<: *archive

