version: '3'
services:
  app:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - APP_VERSION=0.0.0-docker
      - APP_ENVIRONMENT=docker
    ports: 
      - "5000:80"
    volumes:
      - ./src:/app
volumes:
  data_volume: